DWAPlannerROS:
  max_vel_x: 1.0
  min_vel_x: 0.6
  max_vel_theta: 1.0
  min_vel_theta: -1.0

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.10
  
  dwa: true

  pdist_scale: 0.6
  gdist_scale: 0.8

  
