obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.32, 0.32], [0.32, -0.32], [-0.32, -0.32], [-0.32, 0.32]]
robot_radius: 0.3
inflation_radius: 1.0

observation_sources: scan 

scan: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
#distance_sensors: {sensor_frame: base_link, data_type: PointCloud, topic: distance_sensors, marking: true, clearing: false, obstacle_range: 0.3, raytrace_range: 0.4, observation_persistence: 5.0 }
#distance_sensors_clearing: {sensor_frame: base_link, data_type: PointCloud, topic: distance_sensors_clearing, marking: false, clearing: true, raytrace_range: 0.4, observation_persistence: 0.0 }
